# Generated by Django 3.0.8 on 2020-10-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201017_0900'),
        ('users', '0004_auto_20201017_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quizzes_taken',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
