# Generated by Django 3.0.8 on 2020-10-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201017_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identifier used in URL query parameters', max_length=10, null=True, unique=True),
        ),
    ]
