# Generated by Django 3.0.8 on 2020-10-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201017_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='identifier',
            field=models.CharField(help_text='Identifier used in URL query parameters', max_length=10, unique=True),
        ),
    ]
