# Generated by Django 3.0.8 on 2020-10-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201017_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
