# Generated by Django 3.0.8 on 2020-10-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201017_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestion',
            name='answer_status',
            field=models.CharField(blank=True, choices=[('c', 'Correct'), ('w', 'Wrong')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
