# Generated by Django 3.0.8 on 2020-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20201018_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
